<a href="https://colab.research.google.com/github/elizabethavargas/CarMileagePredictor/blob/main/chronic_disease_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create Chronic Disease Datasets
data from https://catalog.data.gov/dataset/u-s-chronic-disease-indicators-cdi

In [3]:
# imports
import pandas as pd

In [6]:
# read file
chronic_disease = pd.read_csv('U.S._Chronic_Disease_Indicators__CDI_.csv')
chronic_disease

<ipython-input-6-c277a456bf45>:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  chronic_disease = pd.read_csv('U.S._Chronic_Disease_Indicators__CDI_.csv')

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2014,2014,AR,Arkansas,SEDD; SID,Asthma,Hospitalizations for asthma,NaN,NaN,Number,...,5,AST,AST3_1,NMBR,GENDER,GENM,NaN,NaN,NaN,NaN
1,2018,2018,CO,Colorado,SEDD; SID,Asthma,Hospitalizations for asthma,NaN,NaN,Number,...,8,AST,AST3_1,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2018,2018,DC,District of Columbia,SEDD; SID,Asthma,Hospitalizations for asthma,NaN,NaN,Number,...,11,AST,AST3_1,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2017,2017,GA,Georgia,SEDD; SID,Asthma,Hospitalizations for asthma,NaN,NaN,Number,...,13,AST,AST3_1,NMBR,GENDER,GENF,NaN,NaN,NaN,NaN
4,2010,2010,MI,Michigan,SEDD; SID,Asthma,Hospitalizations for asthma,NaN,NaN,Number,...,26,AST,AST3_1,NMBR,RACE,HIS,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1185671,2020,2020,WY,Wyoming,BRFSS,Diabetes,Dilated eye examination among adults aged >= 1...,NaN,%,Age-adjusted Prevalence,...,56,DIA,DIA7_0,AGEADJPREV,RACE,WHT,NaN,NaN,NaN,NaN
1185672,2020,2020,WY,Wyoming,BRFSS,Older Adults,Proportion of older adults aged >= 65 years wh...,NaN,%,Crude Prevalence,...,56,OLD,OLD3_1,CRDPREV,RACE,WHT,NaN,NaN,NaN,NaN
1185673,2017,2017,IA,Iowa,BRFSS,Arthritis,Activity limitation due to arthritis among adu...,NaN,%,Age-adjusted Prevalence,...,19,ART,ART2_1,AGEADJPREV,RACE,HIS,NaN,NaN,NaN,NaN
1185674,2020,2020,WY,Wyoming,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,Crude Prevalence,...,56,DIA,DIA2_2,CRDPREV,RACE,HIS,NaN,NaN,NaN,NaN
1185675,2019,2019,RI,Rhode Island,BRFSS,Arthritis,Activity limitation due to arthritis among adu...,NaN,%,Crude Prevalence,...,44,ART,ART2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN

In [8]:
# filter for asthma
asthma = chronic_disease[chronic_disease.Topic == 'Asthma']

# filter for alcohol
alcohol = chronic_disease[chronic_disease.Topic == 'Alcohol']

# filter for alcohol
tobacco = chronic_disease[chronic_disease.Topic == 'Tobacco']

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
194,2017,2017,MA,Massachusetts,NVSS,Alcohol,Chronic liver disease mortality,NaN,NaN,Number,...,25,ALC,ALC6_0,NMBR,GENDER,GENF,NaN,NaN,NaN,NaN
195,2012,2012,NM,New Mexico,NVSS,Alcohol,Chronic liver disease mortality,NaN,"cases per 100,000",Age-adjusted Rate,...,35,ALC,ALC6_0,AGEADJRATE,RACE,API,NaN,NaN,NaN,NaN
196,2015,2015,CO,Colorado,PRAMS,Alcohol,Alcohol use before pregnancy,NaN,%,Crude Prevalence,...,8,ALC,ALC1_2,CRDPREV,RACE,API,NaN,NaN,NaN,NaN
197,2020,2020,HI,Hawaii,NVSS,Alcohol,Chronic liver disease mortality,NaN,NaN,Number,...,15,ALC,ALC6_0,NMBR,RACE,AIAN,NaN,NaN,NaN,NaN
198,2013,2013,IL,Illinois,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,17,ALC,ALC1_1,CRDPREV,RACE,AIAN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1185487,2020,2020,WY,Wyoming,BRFSS,Alcohol,Heavy drinking among women aged 18-44 years,NaN,%,Crude Prevalence,...,56,ALC,ALC5_2,CRDPREV,RACE,WHT,NaN,NaN,NaN,NaN
1185500,2020,2020,WY,Wyoming,BRFSS,Alcohol,Binge drinking frequency among adults aged >= ...,NaN,Number,Mean,...,56,ALC,ALC3_0,MEAN,RACE,OTH,NaN,NaN,NaN,NaN
1185522,2020,2020,WY,Wyoming,BRFSS,Alcohol,Heavy drinking among adults aged >= 18 years,NaN,%,Crude Prevalence,...,56,ALC,ALC5_1,CRDPREV,RACE,OTH,NaN,NaN,NaN,NaN
1185560,2020,2020,WY,Wyoming,BRFSS,Alcohol,Binge drinking intensity among adults aged >= ...,NaN,Number,Age-adjusted Mean,...,56,ALC,ALC4_0,AGEADJMEAN,RACE,HIS,NaN,NaN,NaN,NaN
1185659,2020,2020,WY,Wyoming,BRFSS,Alcohol,Heavy drinking among adults aged >= 18 years,NaN,%,Age-adjusted Prevalence,...,56,ALC,ALC5_1,AGEADJPREV,RACE,WHT,NaN,NaN,NaN,NaN

In [15]:
# save files
asthma.to_csv('asthma_stats.csv')
alcohol.to_csv('alcohol_stats.csv')
tobacco.to_csv('tobacco_stats.csv')

# download files
from google.colab import files
files.download('asthma_stats.csv') 
files.download('alcohol_stats.csv') 
files.download('tobacco_stats.csv')